export enum RandomPhotos {
  GET_RANDOM_PHOTOS_START = "GET_RANDOM_PHOTOS_START",
  GET_RANDOM_PHOTOS_SUCCESS = "GET_RANDOM_PHOTOS_SUCCESS",
  GET_RANDOM_PHOTOS_NEW_SUCCESS = "GET_RANDOM_PHOTOS_NEW_SUCCESS",
  GET_RANDOM_PHOTOS_FAIL = "GET_RANDOM_PHOTOS_FAIL",
}
export enum RandomPhoto {
  GET_RANDOM_PHOTO_START = "GET_RANDOM_PHOTO_START",
  GET_RANDOM_PHOTO_SUCCESS = "GET_RANDOM_PHOTO_SUCCESS",
  GET_RANDOM_PHOTO_NEW_SUCCESS = "GET_RANDOM_PHOTO_NEW_SUCCESS",
  GET_RANDOM_PHOTO_FAIL = "GET_RANDOM_PHOTO_FAIL",
}
