export enum SearchPhotos {
  SEARCH_BY_KEYWORD_START = "SEARCH_BY_KEYWORD_START",
  SEARCH_BY_KEYWORD_SUCCESS = "SEARCH_BY_KEYWORD_SUCCESS",
  SEARCH_BY_KEYWORD_FAIL = "SEARCH_BY_KEYWORD_FAIL",
  SEARCH_ADD_RECENT = "SEARCH_ADD_RECENT",
}
