export enum AllPhotos {
  GET_ALL_PHOTOS_START = "GET_ALL_PHOTOS_START",
  GET_ALL_PHOTOS_SUCCESS = "GET_ALL_PHOTOS_SUCCESS",
  GET_ALL_PHOTOS_NEW_SUCCESS = "GET_ALL_PHOTOS_NEW_SUCCESS",
  GET_ALL_PHOTOS_FAIL = "GET_ALL_PHOTOS_FAIL",
}
